---
title: "R Notebook"
output: html_notebook
---



```{r, message = FALSE, warning = FALSE, include = FALSE}
library(tidyverse)
library(vegan)
library(lubridate)
library(dendextend)
library(here)
library(plotrix)
library(directlabels)
library(cowplot)
library(NbClust)
library(ggdendro)
library(scales)
library(ggtext)
library(factoextra)
library(cluster)


```

Importing all data, but just use 'temp' for most recent version to address reviewer comments

```{r importing data, warning = FALSE, message=FALSE, include = FALSE}
spat <- read_csv(here::here("raw", "spatial.csv")) 
temp <- read_csv(here::here("raw", "Temporal.csv"))
meta <- read_csv(here::here("processed", "metadata.csv"))

spat <- spat %>%
  mutate(date = make_date(year, month, day)) %>%
  select(ufn, date, year, month, day, location, region, site, species.no, forklength, fishweight, corrected.bolus.ww = corrected.ww, phylum, class, order, infraorder, family, genus, plot.taxon.g, plot.taxon.d, plot.taxon, life.stage, DI, count, size, length.avg, corrected.prey.weight = corrected.weight) %>%
  mutate(corrected.prey.weight = as.numeric(corrected.prey.weight))

temp <- temp %>%
 select(ufn, date, year, month, day, location, region, site, species.no, forklength, fishweight, corrected.bolus.ww = corrected.ww, phylum, class, order, infraorder, family, genus, plot.taxon.g, plot.taxon.d, plot.taxon, life.stage, DI, count, size, length.avg, corrected.prey.weight = corrected.weight) %>%
  mutate(month = as.numeric(month), day = as.numeric(day), fishweight = as.numeric(fishweight), length.avg = as.numeric(length.avg))

dat <- full_join(spat, temp) %>%
  mutate(plot.taxon = case_when(plot.taxon == "Euphausiidae" ~ "Euphausiid",
                                TRUE ~ plot.taxon))
```



```{r data wrangle biomass}
# Can run this code with either spat data, temp data, or all data combined, just swap out source file
# Biomass
diet_biom <- temp %>%
  select(ufn, date, year, location, site, region, plot.taxon, corrected.prey.weight) %>%
  mutate(yday = yday(date)) %>%
  unite(ID, c(site, ufn), remove = FALSE) %>%
  filter(!corrected.prey.weight %in% c("NA", "#VALUE!"), !plot.taxon %in% c('NA', 'Nauplius', 'Digested', 'Parasite'), !is.na(plot.taxon)) %>%
  #filter(!ID %in% c("D07_U222", "D07_U242", "D07_U243", "D07_U301", "J07_U596", "J07_U611", "J07_U765")) %>% # if you want to remove outliers that result in too many small diet groups - I've chosen to leave all data in
  mutate(tperiod = case_when(location == "DI" & year == 2015 & yday < 141 ~ "DI_Early", #ydays for each migration timing group based on Brett's cumulative catch over the sampling period using Q1 and Q3
                         location == "DI" & year == 2015 & yday > 140 & yday < 154 ~ "DI_Peak",
                         location == "DI" & yday > 153 ~ "DI_Late",
                         location == "DI" & year == 2016 & yday < 139 ~ "DI_Early",
                         location == "DI" & year == 2016 & yday > 138 & yday < 155 ~ "DI_Peak",
                         location == "JS" & year == 2015 & yday < 148 ~ "JS_Early",
                         location == "JS" & year == 2015 & yday > 147 & yday < 159 ~ "JS_Peak",
                         location == "JS" & year == 2015 & yday > 158 ~ "JS_Late",
                         location == "JS" & year == 2016 & yday < 149 ~ "JS_Early",
                         location == "JS" & year == 2016 & yday > 148 & yday < 164 ~ "JS_Peak",
                         location == "JS" & year == 2016 & yday > 164 ~ "JS_Late")) %>%
  mutate(corrected.prey.weight = as.numeric(corrected.prey.weight)) %>%
  group_by(ID, plot.taxon) %>%
  mutate(total = sum(corrected.prey.weight)) %>%
  select(-corrected.prey.weight) %>%
  ungroup() %>%
  distinct() %>%
  group_by(ID) %>%
  mutate(relbiom = (total/sum(total))) %>%
  mutate(arcsin = ((2/pi)*asin(sqrt(relbiom)))) %>% # data need to be transformed for Bray-Curtis analysis
  select(ID, tperiod, site, region, location, plot.taxon, arcsin) %>%
  mutate(tperiod = factor(tperiod, levels = c("DI_Early", "DI_Peak", "DI_Late", "JS_Early", "JS_Peak", "JS_Late")))

groups <- diet_biom %>%
  group_by(tperiod) %>%
  summarise(n = length(unique(ID)))

#rearranging rows of taxonomic data into columns by plot taxon, making all NA's = 0, selecting only taxonomic columns
clusdata <- spread(diet_biom, key = plot.taxon, value = arcsin) 
clusdata[is.na(clusdata)] <- 0

#converting it to a dataframe and setting rownames as the first column and then only selecting the taxonomic data columns
# as part of the data prep for Bray-Curtis
clusdata <- data.frame(clusdata)
rownames(clusdata) = clusdata[,1]
bc_dat <- clusdata[6:51]

```


```{r}
#Bray-Curtis:----------#

#vegdist uses the vegan package to calculate the distances between variables
bc_dist <- vegdist(bc_dat, method = "bray")

#hclust creates the dendrogram by calculating the amount of dissimilarity between clusters,
# average calculates the distance between all the different values in each group and then averages them
bc_clust <- hclust(bc_dist, method = "average")

##Presence-Absence Version##
## using decostand function in vegan to convert data matrix to presence-absence data
#spat_pa_data <- decostand(clusdata, "pa")
#spat_pa_dist <- vegdist(spat_pa_dat, method = "bray", binary = T)
#spat_bc_clust <- hclust(spat_pa_dist, method = "average")

```

```{r Cluster metadata}
# First identify # of clusters - this is a grey area. Some say to visually inspect dendrogram and choose, others use stats. Here I do both. Use the various stats to look at meaningful #s of clusters (use NbClust as it compares 30 indices) but then within the 2 main clusters (separated mainly by location), you can see that there are 3 subclusters (different migration timing) that have high dissimilarity so have pulled those out for comparison

mydata <- bc_dat

# elbow method using within groups sum of squares and identify 'elbow' in the figure: k = 4
fviz_nbclust(mydata, FUN = hcut, method = "wss")

#Silhouette method which shows k = 9
fviz_nbclust(mydata, FUN = hcut, method = "silhouette")

#Gap statistic method which shows k = 20 (but that's also the kmax used)
#gap_stat <- clusGap(mydata, FUN = hcut, nstart = 25, K.max = 20, B = 500)
#fviz_gap_stat(gap_stat)

# NbClust using 30 indices and the majority rule: suggests 2 clusters. Move ahead with this statistic. 2 Clusters, but visual inspection of dendrogram shows that there are 3 sub clusters in the DI cluster (excluding outliers) that roughly correspond to migration timing. Use k = 8 to identify subclusters and plot in NMDS
NbClust(data = mydata, diss = NULL, distance = "euclidean",
        min.nc = 2, max.nc = 20, method = "average")
 

# plotting the Bray-Curtis dissimilarity, I made it as a dendrogram to flatten out the bottom
den_clust = as.dendrogram(bc_clust)
plot(den_clust)


## METADATA ##
sub_grp <- cutree(den_clust, k = 8) # leave all samples in for plotting dendrogram and filter to remove groups with n<2 for analyses later
table(sub_grp) # tells you how many samples in each cluster

# visually inspect the dendrogram with different numbers of clusters by modifying k=n
den_clust <- den_clust %>%
  color_branches(k=8)
plot(den_clust, ylab = "Bray-Curtis Dissimilarity", ylim = c(0,1))

# Assign cluster names to each cluster number
clusdata1 <- clusdata %>%
  mutate(cluster = sub_grp) %>%
  mutate(cluster = case_when(cluster == 1 ~ "C", # outliers
                             cluster == 2 ~ "A1", # JS
                             cluster == 3 ~ "B3", # DI Late
                             cluster == 4 ~ "B1", # DI Mix
                             cluster == 5 ~ "B2", # DI Early,
                             cluster == 6 ~ "A2", # outliers,
                             cluster == 7 ~ "D", # outliers,
                             cluster == 8 ~ "E")) %>% # outliers
  add_count(cluster) %>%
  select(1:4, 52:53, 5:51)
  

#edit metadata to only contain same ID's as in the fish data
metadata1 <- semi_join(meta, clusdata1, by = "ID")

metadata <- merge(metadata1, clusdata1[,c("ID", "tperiod", "cluster")], by = "ID") %>%
  select(1, 29:30, 2:5, 7:11, 13, 16:28) %>%
  mutate(week = lubridate::week(ymd(date))) %>%
  select(1:12, 27, 13:26) %>%
  unite(ID3, c(location, year), remove = FALSE) %>%
  mutate(time = case_when(grepl("Early", tperiod) ~ "Early",
                          grepl("Peak", tperiod) ~ "Peak",
                          grepl("Late", tperiod) ~ "Late")) %>%
  select(1:2, 29, 5, 3:4, 6:28) 
#write_csv(metadata, "../processed/metadata_with_clusters.csv") # save this version of metadata to use for species comp figures

```


```{r}
#Plotting:------------# For plotting purposes leave all samples in 

# Pull out ID2 (location and time period identifier)
den_meta <- metadata %>%
  select(ID, tperiod, ID3)

# extract dendrogram segment data to colour segments by ID2
dendrogram_data <- dendro_data(den_clust)
dendrogram_segments <- dendrogram_data$segments # contains all dendrogram segment data
head(dendrogram_segments)

# get terminal dendrogram segments
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% # filter for terminal dendrogram ends
 left_join(dendrogram_data$labels, by = "x") %>% # .$labels contains the row names from dist_matrix (i.e., sample_name)
 rename(ID = label) %>%
 left_join(den_meta, by = "ID") %>%
  mutate(tperiod = factor(tperiod, levels = c("DI_Early", "DI_Peak", "DI_Late", "JS_Early", "JS_Peak", "JS_Late")))
# dataframe now contains only terminal dendrogram segments and merged metadata associated with each group

ID_col <- c("DI_Early" = "lightsalmon", "DI_Peak" = "orangered1", "DI_Late" = "firebrick", "JS_Early" = "skyblue", "JS_Peak" = "royalblue2", "JS_Late" = "darkblue")

# Plot the dendrogram with each terminal branch coloured by location_timeperiod
p <- ggplot() +
 geom_segment(data = dendrogram_segments, aes(x=x, y=y, xend=xend, yend=yend)) +
 geom_segment(data = dendrogram_ends, aes(x=x, y=y.x, xend=xend, yend=yend, color = tperiod)) +
 scale_color_manual(values = ID_col) +
  scale_y_reverse(expand = c(0,0.01), limits = c(1,0)) +
  coord_flip() + 
  theme_bw() + 
  theme(legend.title = element_blank(),
        legend.justification = "bottom",  
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  ylab("Distance") +  # flipped x and y coordinates for aesthetic reasons
  #geom_hline(yintercept = 0.89) + # see SIMPER below - the dissimilarity between clusters to get 5 clusters is 87.37% so add vertical line to show 5 groups
  annotate("text", x = 150, y = 0.8, label = "A1", hjust = 0, vjust = 0) + # only showing text for main clusters not the outliers, not sure if this makes things more confusing?
  annotate("text", x = 70, y = 0.8, label = "A2", hjust = 0, vjust = 0) +
  annotate("text", x = 50, y = 0.8, label = "B1", hjust = 0, vjust = 0) +
  annotate("text", x = 20, y = 0.8, label = "B2", hjust = 0, vjust = 0) +
  annotate("text", x = 10, y = 0.8, label = "B3", hjust = 0, vjust = 0) 
   
 p
 #ggsave("../figs/NMDS/relbiom_dend_migrationtime_temp.png", width = 20, height = 20, units = "cm")


```


```{r}

##------ANOSIM/SIMPER-------##
##
# remove clusters with < 2 samples
clusdata2 <- clusdata1 %>%
  filter(n > 2)
rownames(clusdata2) = clusdata2[,1]
bc_dat2 <- clusdata2[8:53]

#edit metadata to only contain same ID's as in the fish data
metadata2 <- semi_join(metadata, clusdata2, by = "ID") %>%
  mutate(stock_1 = replace_na(stock_1, "Unknown")) %>%
  distinct()
  #add_count(stock_1) %>% #If you only want to compare stocks with >2 samples add the following code in and use clusdata3 instead
  #filter(n>2)


#clusdata3 <- semi_join(clusdata2, metadata, by = "ID")
#rownames(clusdata3) = clusdata3[,1]
#bc_dat3 <- clusdata3[8:53]
  

#create the BC dissimilarity matrix
bc_dist <- vegdist(bc_dat2, method = "bray")

detach(metadata2) # will read as error the first time if metadata has not been previously attached - ok
attach(metadata2)

#anosim using our dissimilarity matrix and our grouping variable. Can replace grouping variable with others (e.g. year, location, time period, cluster, etc). Compares within and between group similarity. Significant difference between groups when between group dissimilarity is higher than within group (R score closer to 1)
spat.ano <- anosim(bc_dist, stock_1)
summary(spat.ano)
plot(spat.ano)


#simper analysis using the BC dissimilarity matrix and grouping variable. Produces table with average contribution to dissimilary, avg abundances in groups a and b, and the cumulative sum of the contributions to dissimilarity. Use these values for Table S2.3 in sup mat
options(scipen = 100)
sim <- with(metadata2, simper(bc_dat2, cluster)) 
summary(sim)
sim #lists most influential species and their cumulative contributions

#to get the overall dissimilarity between the groups (where the branches are in the dendrogram)
lapply(sim, FUN = function(x){x$overall})



## To compare diets between migration timing groups within each region
# DI only
DI_dat <- clusdata2 %>%
  filter(location == "DI") %>%
  select(8:53)

DI_meta <- metadata2 %>%
  filter(location == "DI") %>%
  mutate(tperiod = factor(tperiod, levels = c("DI_Early", "DI_Peak", "DI_Late")))

DI_dist <- vegdist(DI_dat, method = "bray")

detach(DI_meta)
attach(DI_meta)

#anosim using our dissimilarity matrix and our grouping variable
spat.ano <- anosim(DI_dist, time)
summary(spat.ano)
plot(spat.ano)

# JS only
JS_dat <- clusdata2 %>%
  filter(location == "JS") %>%
  select(8:53)

JS_meta <- metadata2 %>%
  filter(location == "JS") %>%
  mutate(tperiod = factor(tperiod, levels = c("JS_Early", "JS_Peak", "JS_Late")))

JS_dist <- vegdist(JS_dat, method = "bray")

detach(JS_meta)
attach(JS_meta)

#anosim using our dissimilarity matrix and our grouping variable
spat.ano <- anosim(JS_dist, time)
summary(spat.ano)
plot(spat.ano)
```

```{r}
##
##-------Ordination-----------##
##

metadata <- as.data.frame(metadata2) %>%
  mutate(precip = as.factor(precip), stock_1 = as.factor(stock_1))


# metaMDS calculates the MDS stats. k value is the number of dimensions you want it to plot in
## creating ellipses for clusters, specify how you want the clusters/ellipses drawn in 'ord' by selecting metadata 1-4
# sourced code from http://userweb.eng.gla.ac.uk/umer.ijaz/bioinformatics/ecological.html
set.seed(8)

sol <- metaMDS(bc_dat2, distance = "bray", k=2, trymax = 500, autotransform = FALSE, plot = TRUE, noshare = 0.1)
sol$stress # needs to be below 0.2

NMDS = data.frame(x=sol$point[,1], y = sol$point[,2], ID = as.factor(metadata[,4]), tperiod = as.factor(metadata[,2]), time = as.factor(metadata[,3]), date = metadata[,10], year = as.factor(metadata[,11]), location = as.factor(metadata[,7]), region = as.factor(metadata[,8]), cluster = as.factor(metadata[,5]), stock = as.factor(metadata[,29]))
plot.new()
ord <- ordiellipse(sol, as.factor(metadata[,5]), display = "sites", kind = "sd", conf = 0.95, label = T) # create ellipses for each cluster. Can create ellipses of other grouping variables by changing the metadata column selected
dev.off()

# Quick visualization
plot(sol)
sol


#----
# To explore distribution of diet data along the x and y axes in the ordination (just visualizations - not used in paper)
ggplot(subset(NMDS, year == 2015), aes(x = date, y = x, col = location)) +
  geom_point(position = position_jitter(w = 0.5, h = 0)) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  ggtitle("2015 'x'") +
  scale_x_date(date_breaks = "2 week", labels = date_format("%b-%d"), limits = as.Date(c('2015-05-10', '2015-07-01')))

ggplot(subset(NMDS, year == 2016), aes(x = date, y = x, col = location)) +
  geom_point(position = position_jitter(w = 0.5, h = 0)) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  ggtitle("2016 'x'") +
  scale_x_date(date_breaks = "2 week", labels = date_format("%b-%d"), limits = as.Date(c('2016-05-10', '2016-07-01')))

ggplot(subset(NMDS, year == 2015), aes(x = date, y = y, col = location)) +
  geom_point(position = position_jitter(w = 0.5, h = 0)) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  ggtitle("2015 'y'") +
  scale_x_date(date_breaks = "2 week", labels = date_format("%b-%d"), limits = as.Date(c('2015-05-10', '2015-07-01')))

ggplot(subset(NMDS, year == 2016), aes(x = date, y = y, col = location)) +
  geom_point(position = position_jitter(w = 0.5, h = 0)) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  ggtitle("2016 'y'") +
  scale_x_date(date_breaks = "2 week", labels = date_format("%b-%d"), limits = as.Date(c('2016-05-10', '2016-07-01')))

```

```{r}
##
##-------ENV DATA-------##
##
#First look at the distribution of the env data.. is it normal?
hist(metadata$meanFL)
hist(metadata$set_time)
hist(metadata$meantemp)
hist(metadata$meansal)
hist(metadata$meansecchi)
hist(metadata$z.abundance)
hist(metadata$z.biomass)

#creating environmental matrix using metadata by sample
envdat <- metadata %>%
        select(1, 14:29)
envdat <- data.frame(envdat)
rownames(envdat) = envdat[,1]        
envdat <- envdat[,-1]
envdat <- envdat %>%
  dplyr::rename(SST = meantemp, SSS = meansal, Zooplankton_Abund = z.abundance)


#envfit is a function in package 'vegan' to fit environmental vectors onto an ordination
ef <- envfit(sol, envdat, permu = 999, na.rm = TRUE)
ef

#bioenv find the best subset of environmental variables to have max correlation with community dissimilarites
#for some reason, if I don't include 'use = "complete.obs"' I get 'NA' for meantemp and meansal for their correlations.. not sure what this means? Remove categorical variables, removed week as it had the highest correlation, but JS week numbers are also later than DI so this is likely more a reflection of location than migration timing. Use yday instead for timing
envdat2 <- envdat %>%
  select(-c(stock_1, precip, week))

envmodel <- bioenv(bc_dat2, envdat2, method = "spearman", use = "complete.obs", metric = "euclidean")
envmodel # best model has SST and secchi as leading explanatory variables (highest correlation to community data)
summary(envmodel) 



#creating the data for the env vectors to be overlain on the NMDS - need to have env parameters as rownames
df_envfit<-scores(ef,display=c("vectors"))
df_envfit<-df_envfit*vegan:::ordiArrowMul(df_envfit)
df_envfit<-as.data.frame(df_envfit)
df_envfit <- cbind(df_envfit, env = row.names(df_envfit))
df_envfit <- df_envfit %>%
        filter(env %in% c("secchi", "SST")) # identified as leading variables in the bioenv model
rownames(df_envfit)=df_envfit[,3]
df_envfit <- df_envfit %>%
        select(1:2)


```



```{r}
#Reference: http://stackoverflow.com/questions/13794419/plotting-ordiellipse-function-from-vegan-package-onto-nmds-plot-created-in-ggplo
#Data frame df_ell contains values to show ellipses. It is calculated with function veganCovEllipse which is hidden in vegan package. This function is applied to each level of NMDS (group) and it uses also function cov.wt to calculate covariance matrix.
veganCovEllipse<-function (cov, center = c(0, 0), scale = 1, npoints = 100) 
{
        theta <- (0:npoints) * 2 * pi/npoints
        Circle <- cbind(cos(theta), sin(theta))
        t(center + scale * t(Circle %*% chol(cov)))
}

#Generate ellipse points
df_ell <- data.frame()
for(g in levels(NMDS$cluster)){
        if(g!="" && (g %in% names(ord))){
                
                df_ell <- rbind(df_ell, cbind(as.data.frame(with(NMDS[NMDS$cluster==g,],
                                                                 veganCovEllipse(ord[[g]]$cov,ord[[g]]$center,ord[[g]]$scale)))
                                              ,cluster=g))
        }
}
head(df_ell)


#Generate mean values from NMDS plot groups
NMDS.mean=aggregate(NMDS[,1:2],list(group=NMDS$cluster),mean)


## NMDS PLOT----------------
##Before plotting, run the ENVDAT code above to generate environmental vectors
shape_values <- c(1, 19, 2, 17)
p <- ggplot(data = NMDS, aes(x,y, col = cluster)) +
        geom_point(aes(shape=ID, col = cluster), size = 2.5) + 
        scale_shape_manual(values=shape_values) + 
        geom_path(data = df_ell, aes(x=NMDS1, y = NMDS2), size = 1, linetype = 2, alpha = 0.8) +
        geom_segment(data = df_envfit, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2), arrow = arrow(length = unit(0.25, "cm")), colour = "grey30") +
        geom_text(data = as.data.frame(df_envfit), nudge_y = 0.14, aes(x = NMDS1, y = NMDS2, label = rownames(df_envfit)), colour = "grey30", size = 4) +
        theme_classic() +
        theme(panel.background = element_rect(fill = "white", colour = "grey50")) +
        annotate("text", x = -0.9, y = 2.3, label = "3D stress = 0.16", colour = "grey30") +
        #theme(legend.position = "none") +
        labs(col = "Cluster", shape = "Year") 
p

ggsave("tempdietbiom_nmds_bioenv_bycluster.png", path = "../figs/NMDS", width = 18, height = 14, units = "cm", dpi = 300, type = "cairo")


```

